### ISSUE TITLE
SLS Failure

### ISSUE THREAD

**Issue by ritchie9710** [nishi2go/mas-standalone-install#3]
Hi, script seems to fail on the SLS setup. it reports errors for all the following components:

displayStepHeader 3 "SLS Setup Parameters"

echo "===========SLS Endpoint URL=============="
oc get configmap -n 'ibm-sls' sls-suite-registration -o jsonpath='{.data.url}'
echo ""
echo "===========registration Key=============="
oc get configmap -n 'ibm-sls' sls-suite-registration -o jsonpath='{.data.registrationKey}'
echo ""
echo "===========Certificates=============="
oc get configmap -n 'ibm-sls' sls-suite-registration -o jsonpath='{.data.ca}'
echo ""

**Comment by nishi2go** [comment]
Hi, please upload the installation logs and console outputs of the failure. Of course, you must sanitize your credentials and sensitive info. Thanks.

**Comment by nishi2go** [comment]
Hi, I updated the SLS version from V3.1 to V3.2.1. It had been installed on my environment without any failure. Thanks.

**Comment by ritchie9710** [comment]
Great thanks, I'd not got around to retrying and sending the logs etc, thanks for you help, will try again over the next few days thanks.  Great work on putting this together by the way, makes life a lot simpler
